#!/bin/sh

case "${1}" in
        start)
                /usr/sbin/snapclient -d
                ;;

        stop)
                pkill snapclient
                ;;

        status)
                pidof snapclient
                ;;

        *)
                exit 1
                ;;
esac

